CREATE TABLE IF NOT EXISTS notes (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    uuid VARCHAR(255) NOT NULL,
    title VARCHAR(50) NOT NULL,
    content MEDIUMTEXT NOT NULL,
    updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
