CREATE TABLE IF NOT EXISTS users (
   id INTEGER PRIMARY KEY AUTO_INCREMENT,
   uuid VARCHAR(255) NOT NULL,
   username VARCHAR(50) NOT NULL,
   email VARCHAR(255) UNIQUE NOT NULL,
   hash_password VARCHAR(255) NOT NULL,
   updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS notes (
   id INTEGER PRIMARY KEY AUTO_INCREMENT,
   uuid VARCHAR(255) NOT NULL,
   title VARCHAR(50) NOT NULL,
   content MEDIUMTEXT NOT NULL,
   updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   user_uuid VARCHAR(255),
   FOREIGN KEY (user_uuid) REFERENCES users(uuid)
);